/**
 * Any column type column can be.
 */
export type ColumnType =
  | "bit"
  | "int"
  | "integer"
  | "tinyint"
  | "smallint"
  | "mediumint"
  | "bigint"
  | "float"
  | "double"
  | "double precision"
  | "real"
  | "decimal"
  | "dec"
  | "numeric"
  | "fixed"
  | "bool"
  | "boolean"
  | "date"
  | "datetime"
  | "timestamp"
  | "time"
  | "year"
  | "char"
  | "nchar"
  | "national char"
  | "varchar"
  | "nvarchar"
  | "national varchar"
  | "blob"
  | "text"
  | "tinyblob"
  | "tinytext"
  | "mediumblob"
  | "mediumtext"
  | "longblob"
  | "longtext"
  | "enum"
  | "set"
  | "binary"
  | "varbinary"
  | "json"
  | "geometry"
  | "point"
  | "linestring"
  | "polygon"
  | "multipoint"
  | "multilinestring"
  | "multipolygon"
  | "geometrycollection";
